global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: codelab-monitor

rule_files:
  - "rules.yml"

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090

- job_name: node
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: cadvisor
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cadvisor:8080
    