global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: simple-demo

rule_files:
  - "rules.yml"

scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: node
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.17.0.1:9100

- job_name: demo-app
  metrics_path: /prometheus
  static_configs:
  - targets:
    - 172.17.0.1:9999
    - 172.17.0.1:9998